In [7]:
# This may or may not be necessary for you. Gives python permission to access the internet so we can download libraries.

import ssl
try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context

In [14]:
#import relevant nltk data, functions

import nltk
from nltk import word_tokenize,pos_tag
nltk.download('averaged_perceptron_tagger')
nltk.download('maxent_ne_chunker')
nltk.download('words')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/bcritt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /Users/bcritt/nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package words to /Users/bcritt/nltk_data...
[nltk_data]   Unzipping corpora/words.zip.

True

In [2]:
# Read in a directory of txt files as the corpus using the os library.

import os
corpusdir = '/Users/bcritt/Documents/StanfordProjects/Corpora/Emerson/emerson/'
corpus = []
for infile in os.listdir(corpusdir):
    with open(corpusdir+infile, errors='ignore') as fin:
        corpus.append(fin.read())

In [75]:
#word tokenize, pos tag, and ner tag corpus

ne_tree = nltk.ne_chunk(pos_tag(word_tokenize(corpus[0])))
print(ne_tree)

(S
  (ORGANIZATION SAMUEL/NNP)
  (GPE HOAR/NNP)
  ./.
  “/VB
  (PERSON Magno/NNP)
  southeast/JJ
  judice/NN
  quisque/NN
  tuetur/NN
  ;/:
  Victrix/NNP
  causa/VBP
  deis/NN
  placuit/NN
  sed/VBD
  victa/JJ
  Catoni./NNP
  ”/NN
  A/NNP
  YEAR/NN
  ago/RB
  ,/,
  how/WRB
  often/RB
  did/VBD
  we/PRP
  meet/VB
  Beneath/IN
  these/DT
  elms/NNS
  ,/,
  once/RB
  more/RBR
  in/IN
  sober/NNP
  bloom/NN
  ,/,
  (PERSON Thy/NNP)
  tall/NN
  ,/,
  sad/JJ
  figure/NN
  pacing/VBG
  down/RP
  the/DT
  street/NN
  ,/,
  And/CC
  now/RB
  the/DT
  robin/NN
  sings/NNS
  above/IN
  thy/JJ
  tomb/NN
  !/.
  Thy/NNP
  name/NN
  on/IN
  other/JJ
  shores/NNS
  may/MD
  never/RB
  be/VB
  known/VBN
  ,/,
  Though/IN
  (PERSON Rome/NNP)
  austere/RB
  no/DT
  graver/NN
  consul/NN
  knew/VBD
  ,/,
  But/CC
  (GPE Massachusetts/NNP)
  her/PRP$
  true/JJ
  son/NN
  shall/MD
  own/VB
  ;/:
  Out/NNP
  of/IN
  her/PRP$
  soil/NN
  thy/NN
  hardy/NN
  virtues/NNS
  grew/VBD
  ./.
  She/PRP
  loves/VBZ
  the/DT
  man/NN
  that/WDT
  chose/VBD
  the/DT
  conquered/JJ
  cause/NN
  ,/,
  With/IN
  upright/JJ
  soul/NN
  that/WDT
  bowed/VBD
  to/TO
  God/NNP
  alone/RB
  ;/:
  The/DT
  clean/JJ
  hands/NNS
  that/WDT
  upheld/VBD
  her/PRP
  equal/JJ
  laws/NNS
  ,/,
  The/DT
  old/JJ
  religion/NN
  never/RB
  to/TO
  be/VB
  outgrown/VBN
  ;/:
  The/DT
  cold/JJ
  demeanour/NN
  ,/,
  the/DT
  warm/JJ
  heart/NN
  beneath/NN
  ,/,
  The/DT
  simple/JJ
  grandeur/NN
  of/IN
  thy/JJ
  life/NN
  and/CC
  death/NN
  ./.
  F./NNP
  B./NNP
  SANBORN/NNP
  ./.
  April/NNP
  ,/,
  1857/CD
  ./.
  (ORGANIZATION SAMUEL/NNP)
  HOAR/NNP
  ./.
  HERE/NNP
  is/VBZ
  a/DT
  day/NN
  on/IN
  which/WDT
  more/RBR
  public/JJ
  good/JJ
  or/CC
  evil/JJ
  is/VBZ
  to/TO
  be/VB
  done/VBN
  than/IN
  was/VBD
  ever/RB
  done/VBN
  on/IN
  any/DT
  day/NN
  ./.
  And/CC
  this/DT
  is/VBZ
  the/DT
  pregnant/JJ
  season/NN
  ,/,
  when/WRB
  our/PRP$
  old/JJ
  (PERSON Roman/NNP)
  ,/,
  (PERSON Samuel/NNP Hoar/NNP)
  ,/,
  has/VBZ
  chosen/VBN
  to/TO
  quit/VB
  this/DT
  world/NN
  ./.
  Ab/NNP
  iniquo/JJ
  certamine/NN
  indignabundus/NN
  recessit/NN
  ./.
  He/PRP
  was/VBD
  born/VBN
  under/IN
  a/DT
  (GPE Christian/JJ)
  and/CC
  humane/JJ
  star/NN
  ,/,
  full/JJ
  of/IN
  mansuetude/NN
  and/CC
  nobleness/NN
  ,/,
  honour/NN
  and/CC
  charity/NN
  ;/:
  and/CC
  ,/,
  whilst/VBD
  he/PRP
  was/VBD
  willing/JJ
  to/TO
  face/VB
  every/DT
  disagreeable/JJ
  duty/NN
  ,/,
  whilst/NN
  he/PRP
  dared/VBD
  to/TO
  do/VB
  all/DT
  that/WDT
  might/MD
  beseem/VB
  a/DT
  man/NN
  ,/,
  his/PRP$
  self/NN
  respect/NN
  restrained/VBD
  him/PRP
  from/IN
  any/DT
  foolhardiness/NN
  ./.
  The/DT
  (ORGANIZATION Homeric/NNP)
  heroes/NNS
  ,/,
  when/WRB
  they/PRP
  saw/VBD
  the/DT
  gods/NNS
  mingling/VBG
  in/IN
  the/DT
  fray/NN
  ,/,
  sheathed/VBD
  their/PRP$
  swords/NNS
  ./.
  So/RB
  did/VBD
  not/RB
  he/PRP
  feel/VB
  any/DT
  call/NN
  to/TO
  make/VB
  it/PRP
  a/DT
  contest/NN
  of/IN
  personal/JJ
  strength/NN
  with/IN
  mobs/NN
  or/CC
  nations/NNS
  ;/:
  but/CC
  when/WRB
  he/PRP
  saw/VBD
  the/DT
  day/NN
  and/CC
  the/DT
  gods/NNS
  went/VBD
  against/IN
  him/PRP
  ,/,
  he/PRP
  withdrew/VBD
  ,/,
  but/CC
  with/IN
  an/DT
  unaltered/JJ
  belief/NN
  ./.
  All/DT
  was/VBD
  conquered/VBN
  prœter/NN
  atrocem/NN
  animum/JJ
  Catonis/NNP
  ./.
  At/IN
  the/DT
  time/NN
  when/WRB
  he/PRP
  went/VBD
  to/TO
  (GPE South/NNP Carolina/NNP)
  as/IN
  the/DT
  (ORGANIZATION Commissioner/NNP)
  of/IN
  (GPE Massachusetts/NNP)
  ,/,
  in/IN
  1844/CD
  ,/,
  whilst/VBD
  staying/VBG
  in/IN
  (GPE Charleston/NNP)
  ,/,
  pending/VBG
  his/PRP$
  correspondence/NN
  with/IN
  the/DT
  governor/NN
  and/CC
  the/DT
  legal/JJ
  officers/NNS
  ,/,
  he/PRP
  was/VBD
  repeatedly/RB
  warned/VBN
  that/IN
  it/PRP
  was/VBD
  not/RB
  safe/JJ
  for/IN
  him/PRP
  to/TO
  appear/VB
  in/IN
  public/JJ
  ,/,
  or/CC
  to/TO
  take/VB
  his/PRP$
  daily/JJ
  walk/NN
  ,/,
  as/IN
  he/PRP
  had/VBD
  done/VBN
  ,/,
  unattended/VBN
  by/IN
  his/PRP$
  friends/NNS
  ,/,
  in/IN
  the/DT
  streets/NNS
  of/IN
  the/DT
  city/NN
  ./.
  He/PRP
  was/VBD
  advised/VBN
  to/TO
  withdraw/VB
  to/TO
  private/JJ
  lodgings/NNS
  ,/,
  which/WDT
  were/VBD
  eagerly/RB
  offered/VBN
  him/PRP
  by/IN
  friends/NNS
  ./.
  He/PRP
  rejected/VBD
  the/DT
  advice/NN
  ,/,
  and/CC
  refused/VBD
  the/DT
  offers/NNS
  ,/,
  saying/VBG
  that/IN
  he/PRP
  was/VBD
  old/JJ
  ,/,
  and/CC
  his/PRP$
  life/NN
  was/VBD
  not/RB
  worth/JJ
  much/RB
  ,/,
  but/CC
  he/PRP
  had/VBD
  rather/RB
  the/DT
  boys/NNS
  should/MD
  troll/VB
  his/PRP$
  old/JJ
  head/NN
  like/IN
  a/DT
  football/NN
  in/IN
  their/PRP$
  streets/NNS
  ,/,
  than/IN
  that/IN
  he/PRP
  should/MD
  hide/VB
  it/PRP
  ./.
  And/CC
  he/PRP
  continued/VBD
  the/DT
  uniform/JJ
  practice/NN
  of/IN
  his/PRP$
  daily/JJ
  walk/NN
  into/IN
  all/DT
  parts/NNS
  of/IN
  the/DT
  city/NN
  ./.
  But/CC
  when/WRB
  the/DT
  mob/NN
  of/IN
  (PERSON Charleston/NNP)
  was/VBD
  assembled/VBN
  in/IN
  the/DT
  streets/NNS
  before/IN
  his/PRP$
  hotel/NN
  ,/,
  and/CC
  a/DT
  deputation/NN
  of/IN
  gentlemen/NNS
  waited/VBN
  upon/IN
  him/PRP
  in/IN
  the/DT
  hall/NN
  to/TO
  say/VB
  they/PRP
  had/VBD
  come/VBN
  with/IN
  the/DT
  unanimous/JJ
  voice/NN
  of/IN
  the/DT
  State/NNP
  to/TO
  remove/VB
  him/PRP
  by/IN
  force/NN
  ,/,
  and/CC
  the/DT
  carriage/NN
  was/VBD
  at/IN
  the/DT
  door/NN
  ,/,
  he/PRP
  considered/VBD
  his/PRP$
  duty/NN
  discharged/VBD
  to/TO
  the/DT
  last/JJ
  point/NN
  of/IN
  possibility/NN
  ./.
  The/DT
  force/NN
  was/VBD
  apparent/JJ
  and/CC
  irresistible/JJ
  ;/:
  the/DT
  legal/JJ
  officer/NN
  's/POS
  part/NN
  was/VBD
  up/RB
  ;/:
  it/PRP
  was/VBD
  now/RB
  time/NN
  for/IN
  the/DT
  military/JJ
  officer/NN
  to/TO
  be/VB
  sent/VBN
  ;/:
  and/CC
  he/PRP
  said/VBD
  ,/,
  “/NNP
  Well/NNP
  ,/,
  gentlemen/NNS
  ,/,
  since/IN
  it/PRP
  is/VBZ
  your/PRP$
  pleasure/NN
  to/TO
  use/VB
  force/NN
  ,/,
  I/PRP
  must/MD
  go./VB
  ”/NN
  But/CC
  his/PRP$
  opinion/NN
  was/VBD
  unchanged/JJ
  ./.
  In/IN
  like/JJ
  manner/NN
  now/RB
  ,/,
  when/WRB
  the/DT
  votes/NNS
  of/IN
  the/DT
  (GPE Free/NNP States/NNPS)
  ,/,
  as/IN
  shown/VBN
  in/IN
  the/DT
  recent/JJ
  election/NN
  in/IN
  the/DT
  State/NNP
  of/IN
  (GPE Pennsylvania/NNP)
  ,/,
  had/VBD
  disappointed/VBN
  the/DT
  hopes/NNS
  of/IN
  mankind/NN
  and/CC
  betrayed/VBD
  the/DT
  cause/NN
  of/IN
  freedom/NN
  ,/,
  he/PRP
  considered/VBD
  the/DT
  question/NN
  of/IN
  justice/NN
  and/CC
  liberty/NN
  ,/,
  for/IN
  his/PRP$
  age/NN
  ,/,
  lost/VBN
  ,/,
  and/CC
  had/VBD
  no/DT
  longer/RBR
  the/DT
  will/MD
  to/TO
  drag/VB
  his/PRP$
  days/NNS
  through/IN
  the/DT
  dishonours/NN
  of/IN
  the/DT
  long/JJ
  defeat/NN
  ,/,
  and/CC
  promptly/RB
  withdrew/VBD
  ,/,
  but/CC
  with/IN
  unaltered/JJ
  belief/NN
  ./.
  He/PRP
  was/VBD
  a/DT
  very/RB
  natural/JJ
  ,/,
  but/CC
  a/DT
  very/RB
  high/JJ
  character/NN
  ;/:
  a/DT
  man/NN
  of/IN
  simple/JJ
  tastes/NNS
  ,/,
  plain/NN
  and/CC
  true/JJ
  in/IN
  speech/NN
  ,/,
  with/IN
  a/DT
  clear/JJ
  perception/NN
  of/IN
  justice/NN
  ,/,
  and/CC
  a/DT
  perfect/JJ
  obedience/NN
  thereto/NN
  in/IN
  his/PRP$
  action/NN
  ;/:
  of/IN
  a/DT
  strong/JJ
  understanding/NN
  ,/,
  precise/NN
  and/CC
  methodical/NN
  ,/,
  which/WDT
  gave/VBD
  him/PRP
  great/JJ
  eminence/NN
  in/IN
  the/DT
  legal/JJ
  profession/NN
  ./.
  It/PRP
  was/VBD
  rather/RB
  his/PRP$
  reputation/NN
  for/IN
  severe/JJ
  method/NN
  in/IN
  his/PRP$
  intellect/NN
  than/IN
  any/DT
  special/JJ
  direction/NN
  in/IN
  his/PRP$
  studies/NNS
  that/WDT
  caused/VBD
  him/PRP
  to/TO
  be/VB
  offered/VBN
  the/DT
  mathematical/JJ
  chair/NN
  in/IN
  (ORGANIZATION Harvard/NNP University/NNP)
  ,/,
  when/WRB
  vacant/NN
  in/IN
  1806/CD
  ./.
  The/DT
  severity/NN
  of/IN
  his/PRP$
  logic/NN
  might/MD
  have/VB
  inspired/VBN
  fear/NN
  ,/,
  had/VBD
  it/PRP
  not/RB
  been/VBN
  restrained/VBN
  by/IN
  his/PRP$
  natural/JJ
  reverence/NN
  ,/,
  which/WDT
  made/VBD
  him/PRP
  modest/JJ
  and/CC
  courteous/JJ
  ,/,
  though/IN
  his/PRP$
  courtesy/NN
  had/VBD
  a/DT
  grave/NN
  and/CC
  almost/RB
  military/JJ
  air/NN
  ./.
  He/PRP
  combined/VBD
  a/DT
  uniform/JJ
  self/NN
  respect/NN
  with/IN
  a/DT
  natural/JJ
  reverence/NN
  for/IN
  every/DT
  other/JJ
  man/NN
  ;/:
  so/CC
  that/IN
  it/PRP
  was/VBD
  perfectly/RB
  easy/JJ
  for/IN
  him/PRP
  to/TO
  associate/VB
  with/IN
  farmers/NNS
  ,/,
  and/CC
  with/IN
  plain/NN
  ,/,
  uneducated/JJ
  ,/,
  poor/JJ
  men/NNS
  ,/,
  and/CC
  he/PRP
  had/VBD
  a/DT
  strong/JJ
  ,/,
  unaffected/JJ
  interest/NN
  in/IN
  farms/NNS
  ,/,
  and/CC
  crops/NNS
  ,/,
  and/CC
  weathers/NNS
  ,/,
  and/CC
  the/DT
  common/JJ
  incidents/NNS
  of/IN
  rural/JJ
  life/NN
  ./.
  It/PRP
  was/VBD
  just/RB
  as/IN
  easy/JJ
  for/IN
  him/PRP
  to/TO
  meet/VB
  on/IN
  the/DT
  same/JJ
  floor/NN
  ,/,
  and/CC
  with/IN
  the/DT
  same/JJ
  plain/NN
  courtesy/NN
  ,/,
  men/NNS
  of/IN
  distinction/NN
  and/CC
  large/JJ
  ability/NN
  ./.
  He/PRP
  was/VBD
  fond/NN
  of/IN
  farms/NNS
  and/CC
  trees/NNS
  ,/,
  fond/NN
  of/IN
  birds/NNS
  ,/,
  and/CC
  attentive/JJ
  to/TO
  their/PRP$
  manners/NNS
  and/CC
  habits/NNS
  ;/:
  addicted/VBN
  to/TO
  long/VB
  and/CC
  retired/JJ
  walks/NNS
  ;/:
  temperate/VB
  to/TO
  asceticism/VB
  ,/,
  for/IN
  no/DT
  lesson/NN
  of/IN
  his/PRP$
  experience/NN
  was/VBD
  lost/VBN
  on/IN
  him/PRP
  ,/,
  and/CC
  his/PRP$
  self/NN
  command/NN
  was/VBD
  perfect/JJ
  ./.
  Though/IN
  rich/JJ
  ,/,
  of/IN
  a/DT
  plainness/NN
  and/CC
  almost/RB
  poverty/NN
  of/IN
  personal/JJ
  expenditure/NN
  ,/,
  yet/RB
  liberal/JJ
  of/IN
  his/PRP$
  money/NN
  to/TO
  any/DT
  worthy/JJ
  use/NN
  ,/,
  readily/RB
  lending/VBG
  it/PRP
  to/TO
  young/JJ
  men/NNS
  ,/,
  and/CC
  industrious/JJ
  men/NNS
  ,/,
  and/CC
  by/IN
  no/DT
  means/NNS
  eager/VBP
  to/TO
  reclaim/VB
  of/IN
  them/PRP
  either/CC
  the/DT
  interest/NN
  or/CC
  the/DT
  principal/NN
  ./.
  He/PRP
  was/VBD
  open/JJ
  handed/VBN
  to/TO
  every/DT
  charity/NN
  ,/,
  and/CC
  every/DT
  public/JJ
  claim/NN
  that/WDT
  had/VBD
  any/DT
  show/NN
  of/IN
  reason/NN
  in/IN
  it/PRP
  ./.
  When/WRB
  I/PRP
  talked/VBD
  with/IN
  him/PRP
  one/CD
  day/NN
  of/IN
  some/DT
  inequality/NN
  of/IN
  taxes/NNS
  in/IN
  the/DT
  town/NN
  ,/,
  he/PRP
  said/VBD
  it/PRP
  was/VBD
  his/PRP$
  practice/NN
  to/TO
  pay/VB
  whatever/WDT
  was/VBD
  demanded/VBN
  ;/:
  for/IN
  ,/,
  though/IN
  he/PRP
  might/MD
  think/VB
  the/DT
  taxation/NN
  large/JJ
  and/CC
  very/RB
  unequally/RB
  proportioned/VBN
  ,/,
  yet/RB
  he/PRP
  thought/VBD
  the/DT
  money/NN
  might/MD
  as/RB
  well/RB
  go/VB
  in/IN
  this/DT
  way/NN
  as/IN
  in/IN
  any/DT
  other/JJ
  ./.
  The/DT
  strength/NN
  and/CC
  the/DT
  beauty/NN
  of/IN
  the/DT
  man/NN
  lay/NN
  in/IN
  the/DT
  natural/JJ
  goodness/NN
  and/CC
  justice/NN
  of/IN
  his/PRP$
  mind/NN
  ,/,
  which/WDT
  ,/,
  in/IN
  manhood/NN
  and/CC
  in/IN
  old/JJ
  age/NN
  ,/,
  after/IN
  dealing/VBG
  all/PDT
  his/PRP$
  life/NN
  with/IN
  weighty/JJ
  private/JJ
  and/CC
  public/JJ
  interests/NNS
  ,/,
  left/VBD
  an/DT
  infantile/JJ
  innocence/NN
  ,/,
  of/IN
  which/WDT
  we/PRP
  have/VBP
  no/DT
  second/JJ
  or/CC
  third/JJ
  example/NN
  ,/,
  —/VB
  the/DT
  strength/NN
  of/IN
  a/DT
  chief/NN
  united/JJ
  to/TO
  the/DT
  modesty/NN
  of/IN
  a/DT
  child/NN
  ./.
  He/PRP
  returned/VBD
  from/IN
  courts/NNS
  or/CC
  congresses/NNS
  to/TO
  sit/VB
  down/RP
  ,/,
  with/IN
  unaltered/JJ
  humility/NN
  ,/,
  in/IN
  the/DT
  church/NN
  or/CC
  in/IN
  the/DT
  townhouse/NN
  ,/,
  on/IN
  the/DT
  plain/NN
  wooden/JJ
  bench/NN
  where/WRB
  honour/NN
  came/VBD
  and/CC
  sat/VBD
  down/RB
  beside/RB
  him/PRP
  ./.
  He/PRP
  was/VBD
  a/DT
  man/NN
  in/IN
  whom/WP
  so/RB
  rare/JJ
  a/DT
  spirit/NN
  of/IN
  justice/NN
  visibly/RB
  dwelled/VBD
  ,/,
  that/IN
  if/IN
  one/CD
  had/VBD
  met/VBN
  him/PRP
  in/IN
  a/DT
  cabin/NN
  or/CC
  in/IN
  a/DT
  forest/NN
  he/PRP
  must/MD
  still/RB
  seem/VB
  a/DT
  public/JJ
  man/NN
  ,/,
  answering/VBG
  as/IN
  sovereign/JJ
  state/NN
  to/TO
  sovereign/VB
  state/NN
  ;/:
  and/CC
  might/MD
  easily/RB
  suggest/VB
  (PERSON Milton/NNP)
  's/POS
  picture/NN
  of/IN
  (PERSON John/NNP Bradshaw/NNP)
  ,/,
  that/WDT
  “/VBD
  he/PRP
  was/VBD
  a/DT
  consul/NN
  from/IN
  whom/WP
  the/DT
  fasces/NNS
  did/VBD
  not/RB
  depart/VB
  with/IN
  the/DT
  year/NN
  ,/,
  but/CC
  in/IN
  private/JJ
  seemed/VBD
  ever/RB
  sitting/VBG
  in/IN
  judgement/NN
  on/IN
  kings./NN
  ”/NN
  Everybody/NNP
  knew/VBD
  where/WRB
  to/TO
  find/VB
  him/PRP
  ./.
  What/WP
  he/PRP
  said/VBD
  ,/,
  that/WDT
  would/MD
  he/PRP
  do/VB
  ./.
  But/CC
  he/PRP
  disdained/VBD
  any/DT
  arts/NNS
  in/IN
  his/PRP$
  speech/NN
  :/:
  he/PRP
  was/VBD
  not/RB
  adorned/VBN
  with/IN
  any/DT
  graces/NNS
  of/IN
  rhetoric/NN
  ,/,
  “/NN
  But/CC
  simple/JJ
  truth/NN
  his/PRP$
  utmost/JJ
  skill./NN
  ”/NNP
  So/NNP
  cautious/JJ
  was/VBD
  he/PRP
  ,/,
  and/CC
  tender/NN
  of/IN
  the/DT
  truth/NN
  ,/,
  that/IN
  he/PRP
  sometimes/RB
  wearied/VBD
  his/PRP$
  audience/NN
  with/IN
  the/DT
  pains/NNS
  he/PRP
  took/VBD
  to/TO
  qualify/VB
  and/CC
  verify/VB
  his/PRP$
  statements/NNS
  ,/,
  adding/VBG
  clause/NN
  on/IN
  clause/NN
  to/TO
  do/VB
  justice/NN
  to/TO
  all/DT
  his/PRP$
  conviction/NN
  ./.
  He/PRP
  had/VBD
  little/JJ
  or/CC
  no/DT
  power/NN
  of/IN
  generalisation/NN
  ./.
  But/CC
  a/DT
  plain/JJ
  way/NN
  he/PRP
  had/VBD
  of/IN
  putting/VBG
  his/PRP$
  statement/NN
  with/IN
  all/DT
  his/PRP$
  might/MD
  ,/,
  and/CC
  now/RB
  and/CC
  then/RB
  borrowing/VBG
  the/DT
  aid/NN
  of/IN
  a/DT
  good/JJ
  story/NN
  ,/,
  or/CC
  a/DT
  farmer/NN
  's/POS
  phrase/NN
  ,/,
  whose/WP$
  force/NN
  had/VBD
  imprinted/VBN
  it/PRP
  on/IN
  his/PRP$
  memory/NN
  ,/,
  and/CC
  ,/,
  by/IN
  the/DT
  same/JJ
  token/NN
  ,/,
  his/PRP$
  hearers/NNS
  were/VBD
  bound/VBN
  to/TO
  remember/VB
  his/PRP$
  point/NN
  ./.
  The/DT
  impression/NN
  he/PRP
  made/VBD
  on/IN
  juries/NNS
  was/VBD
  honourable/JJ
  to/TO
  him/PRP
  and/CC
  them/PRP
  ./.
  For/IN
  a/DT
  long/JJ
  term/NN
  of/IN
  years/NNS
  ,/,
  he/PRP
  was/VBD
  at/IN
  the/DT
  head/NN
  of/IN
  the/DT
  bar/NN
  in/IN
  (GPE Middlesex/NNP)
  ,/,
  practising/NN
  ,/,
  also/RB
  ,/,
  in/IN
  the/DT
  adjoining/NN
  counties/NNS
  ./.
  He/PRP
  had/VBD
  one/CD
  side/NN
  or/CC
  the/DT
  other/JJ
  of/IN
  every/DT
  important/JJ
  case/NN
  ,/,
  and/CC
  his/PRP$
  influence/NN
  was/VBD
  reckoned/VBN
  despotic/JJ
  ,/,
  and/CC
  sometimes/RB
  complained/VBD
  of/IN
  as/IN
  a/DT
  bar/NN
  to/TO
  public/JJ
  justice/NN
  ./.
  Many/JJ
  good/JJ
  stories/NNS
  are/VBP
  still/RB
  told/VBN
  of/IN
  the/DT
  perplexity/NN
  of/IN
  jurors/NNS
  who/WP
  found/VBD
  the/DT
  law/NN
  and/CC
  the/DT
  evidence/NN
  on/IN
  one/CD
  side/NN
  ,/,
  and/CC
  yet/RB
  (PERSON Squire/NNP Hoar/NNP)
  had/VBD
  said/VBD
  that/IN
  he/PRP
  believed/VBD
  ,/,
  on/IN
  his/PRP$
  conscience/NN
  ,/,
  his/PRP$
  client/NN
  entitled/VBD
  to/TO
  a/DT
  verdict/NN
  ./.
  And/CC
  what/WP
  (GPE Middlesex/NNP)
  jury/NN
  ,/,
  containing/VBG
  any/DT
  god/JJ
  fearing/VBG
  men/NNS
  in/IN
  it/PRP
  ,/,
  would/MD
  hazard/VB
  an/DT
  opinion/NN
  in/IN
  flat/JJ
  contradiction/NN
  to/TO
  what/WP
  (PERSON Squire/NNP Hoar/NNP)
  believed/VBD
  to/TO
  be/VB
  just/RB
  ?/.
  He/PRP
  was/VBD
  entitled/VBN
  to/TO
  this/DT
  respect/NN
  ;/:
  for/IN
  he/PRP
  discriminated/VBD
  in/IN
  the/DT
  business/NN
  that/WDT
  was/VBD
  brought/VBN
  to/TO
  him/PRP
  ,/,
  and/CC
  would/MD
  not/RB
  argue/VB
  a/DT
  rotten/JJ
  cause/NN
  ;/:
  and/CC
  he/PRP
  refused/VBD
  very/RB
  large/JJ
  sums/NNS
  offered/VBD
  him/PRP
  to/TO
  undertake/VB
  the/DT
  defence/NN
  of/IN
  criminal/JJ
  persons/NNS
  ./.
  His/PRP$
  character/NN
  made/VBD
  him/PRP
  the/DT
  conscience/NN
  of/IN
  the/DT
  community/NN
  in/IN
  which/WDT
  he/PRP
  lived/VBD
  ./.
  And/CC
  in/IN
  many/JJ
  a/DT
  town/NN
  it/PRP
  was/VBD
  asked/VBN
  ,/,
  “/VB
  What/WP
  does/VBZ
  (PERSON Squire/NNP Hoar/NNP)
  think/NN
  of/IN
  this/DT
  ?/.
  ”/NN
  and/CC
  in/IN
  political/JJ
  crises/NNS
  ,/,
  he/PRP
  was/VBD
  entreated/VBN
  to/TO
  write/VB
  a/DT
  few/JJ
  lines/NNS
  to/TO
  make/VB
  known/VBN
  to/TO
  good/JJ
  men/NNS
  in/IN
  (GPE Chelmsford/NNP)
  ,/,
  or/CC
  Marlborough/NNP
  ,/,
  or/CC
  (PERSON Shirley/NNP)
  ,/,
  what/WP
  that/IN
  opinion/NN
  was/VBD
  ./.
  I/PRP
  used/VBD
  to/TO
  feel/VB
  that/IN
  his/PRP$
  conscience/NN
  was/VBD
  a/DT
  kind/NN
  of/IN
  metre/NN
  of/IN
  the/DT
  degree/NN
  of/IN
  honesty/NN
  in/IN
  the/DT
  country/NN
  ,/,
  by/IN
  which/WDT
  on/IN
  each/DT
  occasion/NN
  it/PRP
  was/VBD
  tried/VBN
  ,/,
  and/CC
  sometimes/RB
  found/VBD
  wanting/VBG
  ./.
  I/PRP
  am/VBP
  sorry/JJ
  to/TO
  say/VB
  he/PRP
  could/MD
  not/RB
  be/VB
  elected/VBN
  to/TO
  (ORGANIZATION Congress/NNP)
  a/DT
  second/JJ
  time/NN
  from/IN
  (GPE Middlesex/NNP)
  ./.
  And/CC
  in/IN
  his/PRP$
  own/JJ
  town/NN
  ,/,
  if/IN
  some/DT
  important/JJ
  end/NN
  was/VBD
  to/TO
  be/VB
  gained/VBN
  ,/,
  —/PRP
  as/IN
  ,/,
  for/IN
  instance/NN
  ,/,
  when/WRB
  the/DT
  county/NN
  commissioners/NNS
  refused/VBD
  to/TO
  rebuild/VB
  the/DT
  burned/VBN
  courthouse/NN
  ,/,
  on/IN
  the/DT
  belief/NN
  that/IN
  the/DT
  courts/NNS
  would/MD
  be/VB
  transferred/VBN
  from/IN
  (GSP Concord/NNP)
  to/TO
  (GPE Lowell/NNP)
  ,/,
  —/NNP
  all/DT
  parties/NNS
  combined/VBN
  to/TO
  send/VB
  (PERSON Mr./NNP Hoar/NNP)
  to/TO
  the/DT
  (ORGANIZATION Legislature/NNP)
  ,/,
  where/WRB
  his/PRP$
  presence/NN
  and/CC
  speech/NN
  ,/,
  of/IN
  course/NN
  ,/,
  secured/VBD
  the/DT
  rebuilding/NN
  ;/:
  and/CC
  ,/,
  of/IN
  course/NN
  also/RB
  ,/,
  having/VBG
  answered/VBN
  our/PRP$
  end/NN
  ,/,
  we/PRP
  passed/VBD
  him/PRP
  by/IN
  and/CC
  elected/VBN
  somebody/NN
  else/RB
  at/IN
  the/DT
  next/JJ
  term/NN
  ./.
  His/PRP$
  head/NN
  ,/,
  with/IN
  singular/JJ
  grace/NN
  in/IN
  its/PRP$
  lines/NNS
  ,/,
  had/VBD
  a/DT
  resemblance/NN
  to/TO
  the/DT
  bust/NN
  of/IN
  (GPE Dante/NNP)
  ./.
  He/PRP
  retained/VBD
  to/TO
  the/DT
  last/JJ
  the/DT
  erectness/NN
  of/IN
  his/PRP$
  tall/NN
  but/CC
  slender/NN
  form/NN
  ,/,
  and/CC
  not/RB
  less/VB
  the/DT
  full/JJ
  strength/NN
  of/IN
  his/PRP$
  mind/NN
  ./.
  (PERSON Such/JJ)
  was/VBD
  ,/,
  in/IN
  old/JJ
  age/NN
  ,/,
  the/DT
  beauty/NN
  of/IN
  his/PRP$
  person/NN
  and/CC
  carriage/NN
  ,/,
  as/IN
  if/IN
  the/DT
  mind/NN
  radiated/VBD
  ,/,
  and/CC
  made/VBD
  the/DT
  same/JJ
  impression/NN
  of/IN
  probity/NN
  on/IN
  all/DT
  beholders/NNS
  ./.
  His/PRP$
  beauty/NN
  was/VBD
  pathetic/JJ
  and/CC
  touching/VBG
  in/IN
  these/DT
  latest/JJS
  days/NNS
  ,/,
  and/CC
  ,/,
  as/IN
  now/RB
  appears/VBZ
  ,/,
  it/PRP
  awakened/VBD
  a/DT
  certain/JJ
  tender/NN
  fear/NN
  in/IN
  all/DT
  who/WP
  saw/VBD
  him/PRP
  ,/,
  that/IN
  the/DT
  costly/JJ
  ornament/NN
  of/IN
  our/PRP$
  homes/NNS
  and/CC
  halls/NNS
  and/CC
  streets/NNS
  was/VBD
  speedily/RB
  to/TO
  be/VB
  removed/VBN
  ./.

In [ ]:
#optional tree illustration of NER

!pip3 install svgling
ne_tree

In [80]:
places1

                0     1     2
5       southeast    JJ  None
12           deis    NN  None
76            her  PRP$  None
85           soil    NN  None
358      officers   NNS  None
359             ,     ,  None
364          that    IN  None
372        appear    VB  None
513          come   VBN  None
638             ,     ,  None
639            he   PRP  None
640    considered   VBD  None
649           his  PRP$  None
650           age    NN  None
651             ,     ,  None
652          lost   VBN  None
1487       public    JJ  None
1700        found   VBD  None
1761  transferred   VBN  None
1806          and    CC  None
1808     somebody    NN  None
2558      regions   NNS  None
2560    knowledge    NN  None
2561          not    RB  None

In [27]:
#spacy implementation of NER
!pip3 install spacy && python3 -m spacy download en_core_web_sm
import spacy 
nlp = spacy.load("en_core_web_sm")

Requirement already satisfied: spacy in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (3.5.0)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (1.0.4)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (1.0.9)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (2.0.7)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (3.0.8)
Requirement already satisfied: thinc<8.2.0,>=8.1.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (8.1.7)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (1.1.1)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (2.4.5)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (2.0.8)
Requirement already satisfied: typer<0.8.0,>=0.3.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (0.7.0)
Requirement already satisfied: pathy>=0.10.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (0.10.1)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (6.3.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (4.64.1)
Requirement already satisfied: numpy>=1.15.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (1.24.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (2.28.2)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (1.10.4)
Requirement already satisfied: jinja2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (3.1.2)
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (67.1.0)
Requirement already satisfied: packaging>=20.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (23.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (3.3.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4->spacy) (4.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.0.1)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2022.12.7)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from thinc<8.2.0,>=8.1.0->spacy) (0.7.9)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from thinc<8.2.0,>=8.1.0->spacy) (0.0.4)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from typer<0.8.0,>=0.3.0->spacy) (8.1.3)
Requirement already satisfied: MarkupSafe>=2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from jinja2->spacy) (2.1.2)
Collecting en-core-web-sm==3.5.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 7.3 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: spacy<3.6.0,>=3.5.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from en-core-web-sm==3.5.0) (3.5.0)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (1.0.4)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (1.0.9)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (2.0.7)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (3.0.8)
Requirement already satisfied: thinc<8.2.0,>=8.1.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (8.1.7)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (1.1.1)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (2.4.5)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (2.0.8)
Requirement already satisfied: typer<0.8.0,>=0.3.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (0.7.0)
Requirement already satisfied: pathy>=0.10.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (0.10.1)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (6.3.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (4.64.1)
Requirement already satisfied: numpy>=1.15.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (1.24.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (2.28.2)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (1.10.4)
Requirement already satisfied: jinja2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (3.1.2)
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (67.1.0)
Requirement already satisfied: packaging>=20.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (23.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (3.3.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (4.4.0)

Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (3.0.1)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (2022.12.7)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from thinc<8.2.0,>=8.1.0->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (0.7.9)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from thinc<8.2.0,>=8.1.0->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (0.0.4)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from typer<0.8.0,>=0.3.0->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (8.1.3)
Requirement already satisfied: MarkupSafe>=2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from jinja2->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (2.1.2)
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.5.0
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [59]:
doc = nlp(corpus[0])
ner_output = []
for token in doc:
    ner_output.append(token.text + token.ent_type_)

In [60]:
ner_output

['SAMUEL',
 'HOAR',
 '.',
 '\n\n',
 '“',
 'MagnoGPE',
 'southeast',
 'judice',
 'quisque',
 'tuetur',
 ';',
 '\n\n',
 'VictrixGPE',
 'causa',
 'deis',
 'placuit',
 'sed',
 'victa',
 'CatoniORG',
 '.',
 '”',
 '\n\n\n\n\n\n',
 'ADATE',
 'YEARDATE',
 'agoDATE',
 ',',
 'how',
 'often',
 'did',
 'we',
 'meet',
 '\n\n',
 'Beneath',
 'these',
 'elms',
 ',',
 'once',
 'more',
 'in',
 'sober',
 'bloom',
 ',',
 '\n\n',
 'Thy',
 'tall',
 ',',
 'sad',
 'figure',
 'pacing',
 'down',
 'the',
 'street',
 ',',
 '\n\n',
 'And',
 'now',
 'the',
 'robin',
 'sings',
 'above',
 'thy',
 'tomb',
 '!',
 '\n\n',
 'Thy',
 'name',
 'on',
 'other',
 'shores',
 'may',
 'never',
 'be',
 'known',
 ',',
 '\n\n',
 'Though',
 'RomeGPE',
 'austere',
 'no',
 'graver',
 'consul',
 'knew',
 ',',
 '\n\n',
 'But',
 'MassachusettsGPE',
 'her',
 'true',
 'son',
 'shall',
 'own',
 ';',
 '\n\n',
 'Out',
 'of',
 'her',
 'soil',
 'thy',
 'hardy',
 'virtues',
 'grew',
 '.',
 '\n\n',
 'She',
 'loves',
 'the',
 'man',
 'that',
 'chose',
 'the',
 'conquered',
 'cause',
 ',',
 '\n\n',
 'With',
 'upright',
 'soul',
 'that',
 'bowed',
 'to',
 'God',
 'alone',
 ';',
 '\n\n',
 'The',
 'clean',
 'hands',
 'that',
 'upheld',
 'her',
 'equal',
 'laws',
 ',',
 '\n\n',
 'The',
 'old',
 'religion',
 'never',
 'to',
 'be',
 'outgrown',
 ';',
 '\n\n',
 'The',
 'cold',
 'demeanour',
 ',',
 'the',
 'warm',
 'heart',
 'beneath',
 ',',
 '\n\n',
 'The',
 'simple',
 'grandeur',
 'of',
 'thy',
 'life',
 'and',
 'death',
 '.',
 '\n\n',
 'F.PERSON',
 'B.PERSON',
 'SANBORNPERSON',
 '.',
 '\n\n',
 'AprilDATE',
 ',DATE',
 '1857DATE',
 '.',
 '\n\n\n\n\n\n',
 'SAMUEL',
 'HOAR',
 '.',
 '\n\n',
 'HERE',
 'is',
 'aDATE',
 'dayDATE',
 'on',
 'which',
 'more',
 'public',
 'good',
 'or',
 'evil',
 'is',
 'to',
 'be',
 'done',
 'than',
 'was',
 'ever',
 'done',
 'on',
 'anyDATE',
 'dayDATE',
 '.',
 'And',
 'this',
 'is',
 'the',
 'pregnant',
 'seasonDATE',
 ',',
 'when',
 'our',
 'old',
 'RomanPERSON',
 ',',
 'SamuelPERSON',
 'HoarPERSON',
 ',',
 'has',
 'chosen',
 'to',
 'quit',
 'this',
 'world',
 '.',
 'Ab',
 'iniquo',
 'certamine',
 'indignabundus',
 'recessit',
 '.',
 '\n\n',
 'He',
 'was',
 'born',
 'under',
 'a',
 'ChristianNORP',
 'and',
 'humane',
 'star',
 ',',
 'full',
 'of',
 'mansuetude',
 'and',
 'nobleness',
 ',',
 'honour',
 'and',
 'charity',
 ';',
 'and',
 ',',
 'whilst',
 'he',
 'was',
 'willing',
 'to',
 'face',
 'every',
 'disagreeable',
 'duty',
 ',',
 'whilst',
 'he',
 'dared',
 'to',
 'do',
 'all',
 'that',
 'might',
 'beseem',
 'a',
 'man',
 ',',
 'his',
 'self',
 'respect',
 'restrained',
 'him',
 'from',
 'any',
 'foolhardiness',
 '.',
 'The',
 'HomericORG',
 'heroes',
 ',',
 'when',
 'they',
 'saw',
 'the',
 'gods',
 'mingling',
 'in',
 'the',
 'fray',
 ',',
 'sheathed',
 'their',
 'swords',
 '.',
 'So',
 'did',
 'not',
 'he',
 'feel',
 'any',
 'call',
 'to',
 'make',
 'it',
 'a',
 'contest',
 'of',
 'personal',
 'strength',
 'with',
 'mobs',
 'or',
 'nations',
 ';',
 'but',
 'when',
 'he',
 'saw',
 'theDATE',
 'dayDATE',
 'and',
 'the',
 'gods',
 'went',
 'against',
 'him',
 ',',
 'he',
 'withdrew',
 ',',
 'but',
 'with',
 'an',
 'unaltered',
 'belief',
 '.',
 'All',
 'was',
 'conquered',
 'prœter',
 'atrocem',
 'animum',
 'CatonisORG',
 '.',
 '\n\n',
 'At',
 'the',
 'time',
 'when',
 'he',
 'went',
 'to',
 'SouthGPE',
 'CarolinaGPE',
 'as',
 'the',
 'Commissioner',
 'of',
 'MassachusettsGPE',
 ',',
 'in',
 '1844DATE',
 ',',
 'whilst',
 'staying',
 'in',
 'CharlestonGPE',
 ',',
 'pending',
 'his',
 'correspondence',
 'with',
 'the',
 'governor',
 'and',
 'the',
 'legal',
 'officers',
 ',',
 'he',
 'was',
 'repeatedly',
 'warned',
 'that',
 'it',
 'was',
 'not',
 'safe',
 'for',
 'him',
 'to',
 'appear',
 'in',
 'public',
 ',',
 'or',
 'to',
 'take',
 'his',
 'dailyDATE',
 'walk',
 ',',
 'as',
 'he',
 'had',
 'done',
 ',',
 'unattended',
 'by',
 'his',
 'friends',
 ',',
 'in',
 'the',
 'streets',
 'of',
 'the',
 'city',
 '.',
 'He',
 'was',
 'advised',
 'to',
 'withdraw',
 'to',
 'private',
 'lodgings',
 ',',
 'which',
 'were',
 'eagerly',
 'offered',
 'him',
 'by',
 'friends',
 '.',
 'He',
 'rejected',
 'the',
 'advice',
 ',',
 'and',
 'refused',
 'the',
 'offers',
 ',',
 'saying',
 'that',
 'he',
 'was',
 'old',
 ',',
 'and',
 'his',
 'life',
 'was',
 'not',
 'worth',
 'much',
 ',',
 'but',
 'he',
 'had',
 'rather',
 'the',
 'boys',
 'should',
 'troll',
 'his',
 'old',
 'head',
 'like',
 'a',
 'football',
 'in',
 'their',
 'streets',
 ',',
 'than',
 'that',
 'he',
 'should',
 'hide',
 'it',
 '.',
 'And',
 'he',
 'continued',
 'the',
 'uniform',
 'practice',
 'of',
 'his',
 'dailyDATE',
 'walk',
 'into',
 'all',
 'parts',
 'of',
 'the',
 'city',
 '.',
 'But',
 'when',
 'the',
 'mob',
 'of',
 'CharlestonGPE',
 'was',
 'assembled',
 'in',
 'the',
 'streets',
 'before',
 'his',
 'hotel',
 ',',
 'and',
 'a',
 'deputation',
 'of',
 'gentlemen',
 'waited',
 'upon',
 'him',
 'in',
 'the',
 'hall',
 'to',
 'say',
 'they',
 'had',
 'come',
 'with',
 'the',
 'unanimous',
 'voice',
 'of',
 'the',
 'StateORG',
 'to',
 'remove',
 'him',
 'by',
 'force',
 ',',
 'and',
 'the',
 'carriage',
 'was',
 'at',
 'the',
 'door',
 ',',
 'he',
 'considered',
 'his',
 'duty',
 'discharged',
 'to',
 'the',
 'last',
 'point',
 'of',
 'possibility',
 '.',
 'The',
 'force',
 'was',
 'apparent',
 'and',
 'irresistible',
 ';',
 'the',
 'legal',
 'officer',
 "'s",
 'part',
 'was',
 'up',
 ';',
 'it',
 'was',
 'now',
 'time',
 'for',
 'the',
 'military',
 'officer',
 'to',
 'be',
 'sent',
 ';',
 'and',
 'he',
 'said',
 ',',
 '“',
 'Well',
 ',',
 'gentlemen',
 ',',
 'since',
 'it',
 'is',
 'your',
 'pleasure',
 'to',
 'use',
 'force',
 ',',
 'I',
 'must',
 'go',
 '.',
 '”',
 'But',
 'his',
 'opinion',
 'was',
 'unchanged',
 '.',
 '\n\n',
 'In',
 'like',
 'manner',
 'now',
 ',',
 'when',
 'the',
 'votes',
 'of',
 'theGPE',
 'FreeGPE',
 'StatesGPE',
 ',',
 'as',
 'shown',
 'in',
 'the',
 'recent',
 'election',
 'in',
 'theGPE',
 'StateGPE',
 'ofGPE',
 'PennsylvaniaGPE',
 ',',
 'had',
 'disappointed',
 'the',
 'hopes',
 'of',
 'mankind',
 'and',
 'betrayed',
 'the',
 'cause',
 'of',
 'freedom',
 ',',
 'he',
 'considered',
 'the',
 'question',
 'of',
 'justice',
 'and',
 'liberty',
 ',',
 'for',
 'his',
 'age',
 ',',
 'lost',
 ',',
 'and',
 'had',
 'no',
 'longer',
 'the',
 'will',
 'to',
 'drag',
 'his',
 'days',
 'through',
 'the',
 'dishonours',
 'of',
 'the',
 'long',
 'defeat',
 ',',
 'and',
 'promptly',
 'withdrew',
 ',',
 'but',
 'with',
 'unaltered',
 'belief',
 '.',
 '\n\n',
 'He',
 'was',
 'a',
 'very',
 'natural',
 ',',
 'but',
 'a',
 'very',
 'high',
 'character',
 ';',
 'a',
 'man',
 'of',
 'simple',
 'tastes',
 ',',
 'plain',
 'and',
 'true',
 'in',
 'speech',
 ',',
 'with',
 'a',
 'clear',
 'perception',
 'of',
 'justice',
 ',',
 'and',
 'a',
 'perfect',
 'obedience',
 'thereto',
 'in',
 'his',
 'action',
 ';',
 'of',
 'a',
 'strong',
 'understanding',
 ',',
 'precise',
 'and',
 'methodical',
 ',',
 'which',
 'gave',
 'him',
 'great',
 'eminence',
 'in',
 'the',
 'legal',
 'profession',
 '.',
 'It',
 'was',
 'rather',
 'his',
 'reputation',
 'for',
 'severe',
 'method',
 'in',
 'his',
 'intellect',
 'than',
 'any',
 'special',
 'direction',
 'in',
 'his',
 'studies',
 'that',
 'caused',
 'him',
 'to',
 'be',
 'offered',
 'the',
 'mathematical',
 'chair',
 'in',
 'HarvardORG',
 'UniversityORG',
 ',',
 'when',
 'vacant',
 'in',
 '1806DATE',
 '.',
 'The',
 'severity',
 'of',
 'his',
 'logic',
 'might',
 'have',
 'inspired',
 'fear',
 ',',
 'had',
 'it',
 'not',
 'been',
 'restrained',
 'by',
 'his',
 'natural',
 'reverence',
 ',',
 'which',
 'made',
 'him',
 'modest',
 'and',
 'courteous',
 ',',
 'though',
 'his',
 'courtesy',
 'had',
 'a',
 'grave',
 'and',
 'almost',
 'military',
 'air',
 '.',
 'He',
 'combined',
 'a',
 'uniform',
 'self',
 'respect',
 'with',
 'a',
 'natural',
 'reverence',
 'for',
 'every',
 'other',
 'man',
 ';',
 'so',
 'that',
 'it',
 'was',
 'perfectly',
 'easy',
 'for',
 'him',
 'to',
 'associate',
 'with',
 'farmers',
 ',',
 'and',
 'with',
 'plain',
 ',',
 'uneducated',
 ',',
 'poor',
 'men',
 ',',
 'and',
 'he',
 'had',
 'a',
 'strong',
 ',',
 'unaffected',
 'interest',
 'in',
 'farms',
 ',',
 'and',
 'crops',
 ',',
 'and',
 'weathers',
 ',',
 'and',
 'the',
 'common',
 'incidents',
 'of',
 'rural',
 'life',
 '.',
 'It',
 'was',
 'just',
 'as',
 'easy',
 'for',
 'him',
 'to',
 'meet',
 'on',
 'the',
 'same',
 'floor',
 ',',
 'and',
 'with',
 'the',
 'same',
 'plain',
 'courtesy',
 ',',
 'men',
 'of',
 'distinction',
 'and',
 'large',
 'ability',
 '.',
 'He',
 'was',
 'fond',
 'of',
 'farms',
 'and',
 'trees',
 ',',
 'fond',
 'of',
 'birds',
 ',',
 'and',
 'attentive',
 'to',
 'their',
 'manners',
 'and',
 'habits',
 ';',
 'addicted',
 'to',
 'long',
 'and',
 'retired',
 'walks',
 ';',
 'temperate',
 'to',
 'asceticism',
 ',',
 'for',
 'no',
 'lesson',
 'of',
 'his',
 'experience',
 'was',
 'lost',
 'on',
 'him',
 ',',
 'and',
 'his',
 'self',
 'command',
 'was',
 'perfect',
 '.',
 'Though',
 'rich',
 ',',
 'of',
 'a',
 'plainness',
 'and',
 'almost',
 'poverty',
 'of',
 'personal',
 'expenditure',
 ',',
 'yet',
 'liberal',
 'of',
 'his',
 'money',
 ...]

In [50]:
import pandas as pd

In [67]:
df = pd.DataFrame(ner_output)

In [62]:
df

            0
0      SAMUEL
1        HOAR
2           .
3        \n\n
4           “
...       ...
3377      his
3378  liberal
3379     hand
3380        .
3381   \n\n\n

[3382 rows x 1 columns]

In [63]:
places = df.loc[df[0].str.contains("GPE")]

In [ ]:
places[0] = places[0].str.replace('GPE','')

In [64]:
places

                     0
5             MagnoGPE
12          VictrixGPE
76             RomeGPE
85    MassachusettsGPE
358           SouthGPE
359        CarolinaGPE
364   MassachusettsGPE
372      CharlestonGPE
513      CharlestonGPE
638             theGPE
639            FreeGPE
640          StatesGPE
649             theGPE
650           StateGPE
651              ofGPE
652    PennsylvaniaGPE
1487      MiddlesexGPE
1700    MarlboroughGPE
1761      MiddlesexGPE
1806        ConcordGPE
1808         LowellGPE
2558        AcworthGPE
2560            NewGPE
2561      HampshireGPE

In [68]:
places[0] = places[0].str.replace('GPE','')

/var/folders/k4/nyqsgzvx72vch3f9mypnvg640000gp/T/ipykernel_83223/2533048547.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  places[0] = places[0].str.replace('GPE','')

In [69]:
places

                  0
5             Magno
12          Victrix
76             Rome
85    Massachusetts
358           South
359        Carolina
364   Massachusetts
372      Charleston
513      Charleston
638             the
639            Free
640          States
649             the
650           State
651              of
652    Pennsylvania
1487      Middlesex
1700    Marlborough
1761      Middlesex
1806        Concord
1808         Lowell
2558        Acworth
2560            New
2561      Hampshire

In [86]:
!pip3 install urllib
!pip3 install requests
import urllib
import requests

def geocode2(locality):
    url = 'https://nominatim.openstreetmap.org/search/' + urllib.parse.quote(locality) +'?format=json'
    response = requests.get(url).json()
    if(len(response)!=0):
        return(response[0]['lat'], response[0]['lon'])
    else:
        return('-1')

places['geocoded'] = places[0].apply(geocode2)

SyntaxError: invalid syntax (1839553751.py, line 6)

In [74]:
places

                  0                                   geocoded
5             Magno                  (14.7255675, 121.0390094)
12          Victrix                   (53.1908873, -2.8908955)
76             Rome                   (41.8933203, 12.4829321)
85    Massachusetts                   (42.3788774, -72.032366)
358           South                   (36.638392, 127.6961188)
359        Carolina          (35.90503535, -79.04775326525107)
364   Massachusetts                   (42.3788774, -72.032366)
372      Charleston                  (32.7884363, -79.9399309)
513      Charleston                  (32.7884363, -79.9399309)
638             the          (52.45777545, -1.869209938214711)
639            Free                    (49.1160688, 6.1743816)
640          States                                         -1
649             the          (52.45777545, -1.869209938214711)
650           State                  (42.3588043, -71.0577716)
651              of    (40.881735899999995, 40.27544376928809)
652    Pennsylvania                  (40.9699889, -77.7278831)
1487      Middlesex  (51.546055800000005, -0.2537791389340719)
1700    Marlborough                  (42.3459271, -71.5522874)
1761      Middlesex  (51.546055800000005, -0.2537791389340719)
1806        Concord                    (43.207178, -71.537476)
1808         Lowell                  (42.6414437, -71.3085329)
2558        Acworth                  (34.0659329, -84.6768796)
2560            New                  (38.4278468, -84.8105037)
2561      Hampshire         (51.04483545, -1.2434093597173146)

In [76]:
places.to_csv('places.csv')